### ISSUE TITLE
What happened to SetLogFile?

### ISSUE THREAD

**Issue by goarchit** [spf13/jWalterWeatherman#17]
switch config.GetInt("LogLevel") {
25         case 0:
26                 jww.SetLogThreshold(jww.LevelError)
27                 jww.SetStdoutThreshold(jww.LevelWarn)
28         case 1:
29                 jww.SetLogThreshold(jww.LevelWarn)
30                 jww.SetStdoutThreshold(jww.LevelInfo)
31         case 2:
32                 jww.SetLogThreshold(jww.LevelInfo)
33                 jww.SetStdoutThreshold(jww.LevelInfo)
34         case 3:
35                 jww.SetLogThreshold(jww.LevelDebug)
36                 jww.SetStdoutThreshold(jww.LevelDebug)
37         default:
38                 jww.FATAL.Println("Invalid debug level specified:", config.GetInt("LogLevel"))
39         }
40         jww.SetLogFile(config.GetString("LogFile"))

Results in a ./archit.go:40: undefined: jwalterweatherman.SetLogFile
compilation error.  All the other functions appear to compile fine.

**Comment by bep** [comment]
I refurbished this library a couple of days ago so you can use in a non-global context, with one breaking change.

Use:

```
 SetLogOutput(handle io.Writer)
```
